### PR TITLE
Update package versions on January 2020

### PR DESCRIPTION
**Pull request by MagicPoulp**
This updates packages for the use of auth0 with kotlin

https://auth0.com/blog/authenticating-android-apps-developed-with-kotlin/

### CODE REVIEW

**Comment by MagicPoulp** [comment]
Tested to work both for native screen and browser,

al packages updated

**Comment by brunokrebs** [comment]
Hi there. Thanks for reaching out. I'm wondering... to keep the article in sync with this repo, wouldn't we have to update the article as well?

**Comment by MagicPoulp** [comment]
Is there anything that blocks you from merging the branch? People are already forking from my fork. It would be better if you can merge my code.

I think having updated code with latest libraries is very good.

A blog can still be interesting even if not updated. You should not spend time on maintaining the blog. It would be artificial. Information at a date is still very interesting even several months after a certain date.

Recently the only official auth0 samples I have seen were is pure Java.

**Comment by MagicPoulp** [comment]
Is there anything that blocks you from merging the branch? See my previous comment.

**Pull request closed without merging**
